language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"

before_script:
  - composer self-update
  - composer install --no-scripts --no-interaction --dev
  - composer dump-autoload -o
  - phpenv config-add ./tests/travis.ini

script: phpunit --coverage-text
